external_components:
  - source: github://martydingo/esphome-axp192
    components: [axp192]

font:
  - file: 'fonts/SourceSans.ttf'
    id: sans
    size: 8
  - file: 'fonts/SourceSansItalic.ttf'
    id: sans_italic
    size: 8
  - file: 'fonts/SourceSerif.ttf'
    id: serif
    size: 8
  - file: 'fonts/SourceSerifItalic.ttf'
    id: serif_italic
    size: 8


esphome:
  name: m5stick_c

esp32:
  board: m5stick-c
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "M5Stick C Fallback Hotspot"
    password: !secret wifi_password


captive_portal:
    
spi:
  clk_pin: GPIO13
  mosi_pin: GPIO15

i2c:
   - id: i2c0
     sda: GPIO21
     scl: GPIO22
     scan: True
  
sensor:
  - platform: axp192
    model: M5STICKC
    address: 0x34
    i2c_id: i2c0
    update_interval: 30s
    battery_level:
      name: "M5Stick-C Battery Level"
      id: "m5stick_c_battery_level"

  - platform: wifi_signal
    name: "M5Stick-C WiFi Signal"
    id: "m5stick_c_wifi_signal"

  - platform: uptime
    name: "M5Stick-C Uptime"
    id: "m5stick_c_uptime"

light:
  - platform: monochromatic
    output:  m5stick_c_power_led_output
    name: "M5Stick-C Power LED"
    id: "m5stick_c_power_led"

output:
  - platform: ledc
    pin: 10
    inverted: true
    id: m5stick_c_power_led_output

display:
  - platform: st7735
    model: "INITR_MINI160X80"
    cs_pin: GPIO5
    dc_pin: GPIO23
    reset_pin: GPIO18
    rotation: 270
    device_width: 128
    device_height: 160
    col_start: 0
    row_start: 0
    eight_bit_color: true
    update_interval: 5s
    lambda: |-
      it.print(80, 0, id(sans), TextAlign::TOP_CENTER, "M5Stick Test");